name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  test:
    # Frontend code-base workflow test first
    uses: ./.github/workflows/test.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          region: eu-north-1
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-277707125544
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          version_label: ${{ github.sha }}
