name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Test with Jest
        uses: ./.github/workflows/test.yml
        with:
          entry-point: ./docker-exp-app
