name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test frontend codebase
        uses: ./.github/workflows/test.yml
